spring.application.name=server

spring.datasource.url=jdbc:postgresql://localhost:5432/tuyenshop
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

tuyenshop.app.jwtSecret=TuyenShopSecretKeyWhichIsVeryLongAndSecureEnoughForHS256AlgorithmTuyenShopSecretKeyWhichIsVeryLongAndSecureEnoughForHS256Algorithm
tuyenshop.app.jwtExpirationMs=86400000

spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8080

# VNPAY Configuration
vnpay.tmnCode=YOUR_VNPAY_TMN_CODE
vnpay.hashSecret=YOUR_VNPAY_HASH_SECRET
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/api/payment/vnpay_return
vnpay.apiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
